// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./components/breadcrumbs/Breadcrumbs.vue')['default']
    Card: typeof import('./components/cards/card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dropdown: typeof import('./components/buttons/Dropdown.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PageDescription: typeof import('./components/typography/PageDescription.vue')['default']
    PageTitle: typeof import('./components/typography/PageTitle.vue')['default']
    ProjectsPicker: typeof import('./components/projects/ProjectsPicker.vue')['default']
    ProjectsTable: typeof import('./components/projects/ProjectsTable.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
