// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bread: typeof import('./components/breadcrumbs/bread.vue')['default']
    Breadcrumbs: typeof import('./components/breadcrumbs/Breadcrumbs.vue')['default']
    Card: typeof import('./components/cards/card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PageTitle: typeof import('./components/typography/PageTitle.vue')['default']
    Projects: typeof import('./components/projects/projects.vue')['default']
    ProjectsTable: typeof import('./components/projects/ProjectsTable.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
